### ISSUE TITLE
build-vpn.sh fails when using AMI 4.9.32-15.41.amzn1.x86_64

### ISSUE THREAD

**Issue by opedroso** [jenh/sevenminutevpn#1]
Just tried today (Sep 4th, 2017) and Lightsail script fails around here:
fatal: destination path 'sevenminutevpn' already exists and is not an empty directory
Error opening Certificate /etc/openvpn/easy-rsa/pki/ca.crt

**Comment by jenh** [comment]
Fixed in 85ec634. Issue was that we were assuming easyrsa places in /etc/openvpn/easy-rsa if $EASYRSA_PKI wasn't specified; this behavior changed in EasyRSA, which now places in the current directory by default unless explicitly set in vars. Thanks so much for reporting this!
