### ISSUE TITLE
[QUESTION] p12 file requirement

### ISSUE THREAD

**Issue by 1upbyte** [jenh/sevenminutevpn#2]
would it be possible to omit the p12 file requirement, even if insecurely? my chromebook is managed and doesn't allow for importing and binding person certificates (although it does allow server certificates if that could help)

**Comment by 1upbyte** [comment]
i did it! using [this](https://www.saadismail.net/installing-openvpn-user-with-username-password-authentication/) guide, along with [this](https://github.com/Nyr/openvpn-install/) script to set up openvpn i was able to do it. I took the server.conf and the client.conf from Saad's guide and stuck it in Nyr's thing. idk how janky itll be, but it works!

**Comment by jenh** [comment]
Awesome! Glad to hear it worked and thanks for sharing the solution for anyone else in the same situation, Pablo! :)
